### ISSUE TITLE
IO exception

### ISSUE THREAD

**Issue by Pouja** [JS-DevTools/coverage-istanbul-loader#5]
There can be an io exception when there is no sourcemap given nor there is a source map file.
The following stacktrace will be reproduced (I have ommited some parts of the file path) :
```
ERROR in ./src/main/javascript/app/components/path/traffic-diensten.component.js
Module build failed (from ./node_modules/coverage-istanbul-loader/lib/index.js):
Error: An error occurred while trying to read the map file at \path\src\main\javascript\app\components\path\traffic-diensten.component.js.map
Error: ENOENT: no such file or directory, open '\path\src\main\javascript\app\components\path\traffic-diensten.component.js.map'
at readFromFileMap (\path\node_modules\convert-source-map\index.js:40:11)
at new Converter (\path\node_modules\convert-source-map\index.js:47:32)
at Object.exports.fromMapFileComment (\path\node_modules\convert-source-map\index.js:110:10)
at Object.exports.fromMapFileSource (\path\node_modules\convert-source-map\index.js:122:22)
at Object.default_1 (\path\node_modules\coverage-istanbul-loader\src\index.ts:28:26)
@ ./src/main/javascript/app/components/overzichten/overzichten.module.ts 92:0-94 108:807-840
@ ./src/main/javascript/app/components/components.ts
@ ./src/main/javascript/app/app.angularjs.module.ts
@ ./src/main/javascript/flow-tests.ts
```

See also: https://github.com/JS-DevTools/coverage-istanbul-loader/blob/master/src/index.ts#L25

**Comment by JamesMessinger** [comment]
Thanks for the bug report!  Do you have time to submit a PR?

**Comment by Pouja** [comment]
I actually do. I'll try to come with a PR this week.
